# Generated by Django 3.1.7 on 2021-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210417_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
