# Generated by Django 3.1.7 on 2021-05-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_questionanswer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
