# Generated by Django 3.1.7 on 2021-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
